[project]
name = "chatbot"
version = "0.1.0"
description = ""
authors = [{ name = "Слепцов Денис", email = "hurrdurrrderp@gmail.com" }]
license = { text = "WTFPL" }
requires-python = ">=3.12,<3.15"
dependencies = [
    "langchain (>=1.2.11,<2.0.0)",
    "faiss-cpu (>=1.13.2,<2.0.0)",
    "torch (>=2.11.0,<3.0.0)",
    "sentence-transformers (>=5.4.1,<6.0.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[tool.poetry.dependencies]
torch = { source = "pytorch_cpu" }

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)"
]
